main: com.LucasRomier.BetterMobAI.MobAI
version: "3.0 alpha"
name: BetterMobAI
author: whereisthemonkey

commands:
  BetterMobAI:
    permission: BetterMobAI.reload
  
permissions:
  BetterMobAI.reload:
    description: Allows to reload the plugin
    default: op